/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-11-06 06:03:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Home</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("\t<link rel=\"icon\" href=\"img/logo.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"50\">\r\n");
      out.write("\t<!--Barra de navegacion-->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\"  >\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"index.html\" style=\"font-size: 20px\">\r\n");
      out.write("\t\t<img src=\"img/logo.png\" width=\"30\" height=\"34\" class=\"d-inline-block align-top mr-2\" alt=\"\">\r\n");
      out.write("\t\tGreenLight\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarText\">\r\n");
      out.write("\t\t\t<!--Lado Izquierdo-->\r\n");
      out.write("\t\t    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t      \t<li class=\"nav-item\">\r\n");
      out.write("\t\t        \t<a class=\"nav-link\" href=\"#firstSection\">Inicio<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("\t\t      \t</li>\r\n");
      out.write("\t\t      \t<li class=\"nav-item\">\r\n");
      out.write("\t\t        \t<a class=\"nav-link\" href=\"#secondSection\">Quienes somos</a>\r\n");
      out.write("\t\t      \t</li>\t      \t\r\n");
      out.write("\t\t      \t<li class=\"nav-item\">\r\n");
      out.write("\t\t        \t<a class=\"nav-link\" href=\"#thirdSection\">Patrocinadores</a>\r\n");
      out.write("\t\t      \t</li>\r\n");
      out.write("\t\t      \t<li class=\"nav-item\">\r\n");
      out.write("\t\t        \t<a class=\"nav-link\" href=\"#fourtSection\">Terminos y Condiciones</a>\r\n");
      out.write("\t\t      \t</li>\r\n");
      out.write("\t\t    </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t    <!--Lado Derecho-->\r\n");
      out.write("\t\t    <ul class=\"navbar-nav link-nav\">\r\n");
      out.write("\t\t    \t<li class=\"nav-item\">\r\n");
      out.write("\t\t    \t\t<a class=\"nav-link\" href=\"pages/login.jsp\">Iniciar Sesión</a>\t\r\n");
      out.write("\t\t    \t</li>\r\n");
      out.write("\t\t    \t<li class=\"nav-item\">\r\n");
      out.write("\t\t    \t\t<a class=\"nav-link\" href=\"pages/nuevaCuenta.jsp\">¿Eres nuevo?</a>\r\n");
      out.write("\t\t    \t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Banner-->\r\n");
      out.write("\t<div  style=\"width: 100%;\" class=\"mt-5\"  >\r\n");
      out.write("\t\t<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t  \t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t  \t\t</ol>\r\n");
      out.write("\t\t  \t<div class=\"carousel-inner\" style=\"height: auto;\">\r\n");
      out.write("\t\t\t    <div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t      <img class=\"d-block w-100\" src=\"img/banner.png\" alt=\"First slide\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"carousel-item\">\r\n");
      out.write("\t\t\t      <img class=\"d-block w-100\" src=\"img/banner3.png\" alt=\"Second slide\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"carousel-item\">\r\n");
      out.write("\t\t\t      <img class=\"d-block w-100\" src=\"img/banner2.png\" alt=\"Third slide\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t\t<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t    <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t    <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--Cuerpo de la pagina - Inicio -->\r\n");
      out.write("\t<div id=\"firstSection\" class=\"container\">\r\n");
      out.write("\t\t<div class=\"row mt-5 mb-5\"  >\r\n");
      out.write("\t\t\t<!--Descripcion del servicio-->\r\n");
      out.write("\t\t\t<div class=\"col-6\">\r\n");
      out.write("\t\t\t\t<div id=\"accordion\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t  \t<div class=\"card\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"card-header\" role=\"tab\" id=\"headingOne\">\r\n");
      out.write("\t\t\t\t      \t\t<h5 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t        \t<a class=\"text-gl\" data-toggle=\"collapse\" href=\"#collapseOne\" aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("\t\t\t\t          \tBienvenidos\r\n");
      out.write("\t\t\t\t        \t</a>\r\n");
      out.write("\t\t\t\t      \t\t</h5>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t    \t<div id=\"collapseOne\" class=\"collapse show\" role=\"tabpanel\" aria-labelledby=\"headingOne\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t      \t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. \r\n");
      out.write("\t\t\t\t\t        Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla \r\n");
      out.write("\t\t\t\t\t        assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. \r\n");
      out.write("\t\t\t\t\t        Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.\r\n");
      out.write("\t\t\t\t      \t\t</div>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  \t<div class=\"card\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"card-header\" role=\"tab\" id=\"headingTwo\">\r\n");
      out.write("\t\t\t\t      \t\t<h5 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t        \t<a class=\"collapsed text-gl\" data-toggle=\"collapse\" href=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("\t\t\t\t          \t¿Cómo empezar?\r\n");
      out.write("\t\t\t\t        \t</a>\r\n");
      out.write("\t\t\t\t      \t\t</h5>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t    \t<div id=\"collapseTwo\" class=\"collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t      \t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t        \tAnim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. \r\n");
      out.write("\t\t\t\t\t        Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla \r\n");
      out.write("\t\t\t\t\t        assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. \r\n");
      out.write("\t\t\t\t\t        Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.\r\n");
      out.write("\t\t\t\t     \t \t</div>\r\n");
      out.write("\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  \t<div class=\"card\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"card-header\" role=\"tab\" id=\"headingThree\">\r\n");
      out.write("\t\t\t\t      \t\t<h5 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t        \t<a class=\"collapsed text-gl\" data-toggle=\"collapse\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("\t\t\t\t          \t¿Cúales son mis beneficios?\r\n");
      out.write("\t\t\t\t        \t</a>\r\n");
      out.write("\t\t\t\t      \t\t</h5>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t    \t<div id=\"collapseThree\" class=\"collapse\" role=\"tabpanel\" aria-labelledby=\"headingThree\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t      \t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t        \tAnim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. \r\n");
      out.write("\t\t\t\t\t        Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla \r\n");
      out.write("\t\t\t\t\t        assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. \r\n");
      out.write("\t\t\t\t\t        Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.\r\n");
      out.write("\t\t\t\t      \t\t</div>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--Captando al cliente-->\r\n");
      out.write("\t\t\t<div class=\"col-6\">\r\n");
      out.write("\t\t\t\t<div class=\"col-11 text-center mt-5 ml-2\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/logo.png\" width=\"110\" height=\"126\" class=\"d-inline-block align-top\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"mt-4\">Sé parte de nuestra gran familia.</h5>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-login mt-5 w-100 col-6\" href=\"pages/nuevaCuenta.jsp\">Crear una cuenta</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--Quienes somos-->\r\n");
      out.write("\t<div id=\"secondSection\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>Section 4 Submenu 2</h1>\r\n");
      out.write("\t  \t<p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>\r\n");
      out.write("\t  \t<p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--Patrocinadores-->\r\n");
      out.write("\t<div id=\"thirdSection\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>Section 4 Submenu 2</h1>\r\n");
      out.write("\t  \t<p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>\r\n");
      out.write("\t  \t<p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\t<!--Terminos y Condiciones-->\r\n");
      out.write("\t<div id=\"fourtSection\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>Section 4 Submenu 2</h1>\r\n");
      out.write("\t  \t<p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>\r\n");
      out.write("\t  \t<p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!--Librerias - No sacar-->\r\n");
      out.write("<div>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\" integrity=\"sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\" integrity=\"sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js\" integrity=\"sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
