/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-11-06 06:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dashboard.paciente;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>GLD Paciente</title>\r\n");
      out.write("  <!-- Bootstrap core CSS-->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom fonts for this template-->\r\n");
      out.write("  <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <!-- Page level plugin CSS-->\r\n");
      out.write("  <link href=\"vendor/datatables/dataTables.bootstrap4.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom styles for this template-->\r\n");
      out.write("  <link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Logo icon -->\r\n");
      out.write("  <link rel=\"icon\" href=\"../../img/logo.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"fixed-nav sticky-footer bg-dark\" id=\"page-top\">\r\n");
      out.write("  <!-- Navigation-->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\">Greenlight - Dashboard</a>\r\n");
      out.write("\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\r\n");
      out.write("      <!--Nav Options - Left -->\r\n");
      out.write("      <ul class=\"navbar-nav navbar-sidenav\" id=\"exampleAccordion\">\r\n");
      out.write("\r\n");
      out.write("        <!-- This is our project - init-->\r\n");
      out.write("        <li class=\"nav-item\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Dashboard\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"index.jsp\">\r\n");
      out.write("            <i class=\"fa fa-fw fa-chevron-right\"></i>\r\n");
      out.write("            <span class=\"nav-link-text\">Inicio</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Link\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"pages/editar.jsp\">\r\n");
      out.write("            <i class=\"fa fa-fw fa-pencil-square-o\"></i>\r\n");
      out.write("            <span class=\"nav-link-text\">Editar</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Link\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"pages/citas.jsp\">\r\n");
      out.write("            <i class=\"fa fa-fw fa-medkit\"></i>\r\n");
      out.write("            <span class=\"nav-link-text\">Citas</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!--close nav options project -->\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav sidenav-toggler\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link text-center\" id=\"sidenavToggler\">\r\n");
      out.write("            <i class=\"fa fa-fw fa-angle-left\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- Nav Notification - Top Right-->\r\n");
      out.write("      <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("            <i class=\"fa fa-fw fa-sign-out\"></i>Logout</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <!-- Breadcrumbs-->\r\n");
      out.write("      <ol class=\"breadcrumb\">\r\n");
      out.write("        <li class=\"breadcrumb-item\">\r\n");
      out.write("          <a href=\"index.jsp\">Dashboard</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"breadcrumb-item active\">Inicio</li>\r\n");
      out.write("      </ol>\r\n");
      out.write("\r\n");
      out.write("      <!-- Icon Cards-->\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-3\">\r\n");
      out.write("          <div class=\"card text-white bg-primary o-hidden h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"card-body-icon\">\r\n");
      out.write("                <i class=\"fa fa-fw fa-comments\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"mr-5\">26 New Messages!</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\r\n");
      out.write("              <span class=\"float-left\">View Details</span>\r\n");
      out.write("              <span class=\"float-right\">\r\n");
      out.write("                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("              </span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-3\">\r\n");
      out.write("          <div class=\"card text-white bg-warning o-hidden h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"card-body-icon\">\r\n");
      out.write("                <i class=\"fa fa-fw fa-list\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"mr-5\">11 New Tasks!</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\r\n");
      out.write("              <span class=\"float-left\">View Details</span>\r\n");
      out.write("              <span class=\"float-right\">\r\n");
      out.write("                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("              </span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-3\">\r\n");
      out.write("          <div class=\"card text-white bg-success o-hidden h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"card-body-icon\">\r\n");
      out.write("                <i class=\"fa fa-fw fa-shopping-cart\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"mr-5\">123 New Orders!</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\r\n");
      out.write("              <span class=\"float-left\">View Details</span>\r\n");
      out.write("              <span class=\"float-right\">\r\n");
      out.write("                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("              </span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-3\">\r\n");
      out.write("          <div class=\"card text-white bg-danger o-hidden h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"card-body-icon\">\r\n");
      out.write("                <i class=\"fa fa-fw fa-support\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"mr-5\">13 New Tickets!</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\r\n");
      out.write("              <span class=\"float-left\">View Details</span>\r\n");
      out.write("              <span class=\"float-right\">\r\n");
      out.write("                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("              </span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Card Columns Example Social Feed-->\r\n");
      out.write("          <div class=\"mb-0 mt-4\">\r\n");
      out.write("            <i class=\"fa fa-newspaper-o\"></i> News Feed</div>\r\n");
      out.write("          <hr class=\"mt-2\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card-columns\">\r\n");
      out.write("            <!-- Example Social Card-->\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img class=\"card-img-top img-fluid w-100\" src=\"https://unsplash.it/700/450?image=610\" alt=\"\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"card-title mb-1\"><a href=\"#\">David Miller</a></h6>\r\n");
      out.write("                <p class=\"card-text small\">These waves are looking pretty good today!\r\n");
      out.write("                  <a href=\"#\">#surfsup</a>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body py-2 small\">\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-thumbs-up\"></i>Like</a>\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-comment\"></i>Comment</a>\r\n");
      out.write("                <a class=\"d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-share\"></i>Share</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body small bg-faded\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h6 class=\"mt-0 mb-1\"><a href=\"#\">John Smith</a></h6>Very nice! I wish I was there! That looks amazing!\r\n");
      out.write("                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                      <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#\">Like</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"list-inline-item\">·</li>\r\n");
      out.write("                      <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#\">Reply</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"media mt-3\">\r\n");
      out.write("                      <a class=\"d-flex pr-3\" href=\"#\">\r\n");
      out.write("                        <img src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <div class=\"media-body\">\r\n");
      out.write("                        <h6 class=\"mt-0 mb-1\"><a href=\"#\">David Miller</a></h6>Next time for sure!\r\n");
      out.write("                        <ul class=\"list-inline mb-0\">\r\n");
      out.write("                          <li class=\"list-inline-item\">\r\n");
      out.write("                            <a href=\"#\">Like</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li class=\"list-inline-item\">·</li>\r\n");
      out.write("                          <li class=\"list-inline-item\">\r\n");
      out.write("                            <a href=\"#\">Reply</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-footer small text-muted\">Posted 32 mins ago</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Example Social Card-->\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img class=\"card-img-top img-fluid w-100\" src=\"https://unsplash.it/700/450?image=180\" alt=\"\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"card-title mb-1\"><a href=\"#\">John Smith</a></h6>\r\n");
      out.write("                <p class=\"card-text small\">Another day at the office...\r\n");
      out.write("                  <a href=\"#\">#workinghardorhardlyworking</a>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body py-2 small\">\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-thumbs-up\"></i>Like</a>\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-comment\"></i>Comment</a>\r\n");
      out.write("                <a class=\"d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-share\"></i>Share</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body small bg-faded\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h6 class=\"mt-0 mb-1\"><a href=\"#\">Jessy Lucas</a></h6>Where did you get that camera?! I want one!\r\n");
      out.write("                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                      <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#\">Like</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"list-inline-item\">·</li>\r\n");
      out.write("                      <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#\">Reply</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-footer small text-muted\">Posted 46 mins ago</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Example Social Card-->\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img class=\"card-img-top img-fluid w-100\" src=\"https://unsplash.it/700/450?image=281\" alt=\"\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"card-title mb-1\"><a href=\"#\">Jeffery Wellings</a></h6>\r\n");
      out.write("                <p class=\"card-text small\">Nice shot from the skate park!\r\n");
      out.write("                  <a href=\"#\">#kickflip</a>\r\n");
      out.write("                  <a href=\"#\">#holdmybeer</a>\r\n");
      out.write("                  <a href=\"#\">#igotthis</a>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body py-2 small\">\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-thumbs-up\"></i>Like</a>\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-comment\"></i>Comment</a>\r\n");
      out.write("                <a class=\"d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-share\"></i>Share</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-footer small text-muted\">Posted 1 hr ago</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Example Social Card-->\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img class=\"card-img-top img-fluid w-100\" src=\"https://unsplash.it/700/450?image=185\" alt=\"\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"card-title mb-1\"><a href=\"#\">David Miller</a></h6>\r\n");
      out.write("                <p class=\"card-text small\">It's hot, and I might be lost...\r\n");
      out.write("                  <a href=\"#\">#desert</a>\r\n");
      out.write("                  <a href=\"#\">#water</a>\r\n");
      out.write("                  <a href=\"#\">#anyonehavesomewater</a>\r\n");
      out.write("                  <a href=\"#\">#noreally</a>\r\n");
      out.write("                  <a href=\"#\">#thirsty</a>\r\n");
      out.write("                  <a href=\"#\">#dehydration</a>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body py-2 small\">\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-thumbs-up\"></i>Like</a>\r\n");
      out.write("                <a class=\"mr-3 d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-comment\"></i>Comment</a>\r\n");
      out.write("                <a class=\"d-inline-block\" href=\"#\">\r\n");
      out.write("                  <i class=\"fa fa-fw fa-share\"></i>Share</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr class=\"my-0\">\r\n");
      out.write("              <div class=\"card-body small bg-faded\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h6 class=\"mt-0 mb-1\"><a href=\"#\">John Smith</a></h6>The oasis is a mile that way, or is that just a mirage?\r\n");
      out.write("                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                      <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#\">Like</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"list-inline-item\">·</li>\r\n");
      out.write("                      <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#\">Reply</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"media mt-3\">\r\n");
      out.write("                      <a class=\"d-flex pr-3\" href=\"#\">\r\n");
      out.write("                        <img src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <div class=\"media-body\">\r\n");
      out.write("                        <h6 class=\"mt-0 mb-1\"><a href=\"#\">David Miller</a></h6>\r\n");
      out.write("                        <img class=\"img-fluid w-100 mb-1\" src=\"https://unsplash.it/700/450?image=789\" alt=\"\">I'm saved, I found a cactus. How do I open this thing?\r\n");
      out.write("                        <ul class=\"list-inline mb-0\">\r\n");
      out.write("                          <li class=\"list-inline-item\">\r\n");
      out.write("                            <a href=\"#\">Like</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li class=\"list-inline-item\">·</li>\r\n");
      out.write("                          <li class=\"list-inline-item\">\r\n");
      out.write("                            <a href=\"#\">Reply</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-footer small text-muted\">Posted yesterday</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /Card Columns-->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Example Notifications Card-->\r\n");
      out.write("          <div class=\"card mb-3\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("              <i class=\"fa fa-bell-o\"></i> Feed Example</div>\r\n");
      out.write("            <div class=\"list-group list-group-flush small\">\r\n");
      out.write("              <a class=\"list-group-item list-group-item-action\" href=\"#\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3 rounded-circle\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <strong>David Miller</strong>posted a new article to\r\n");
      out.write("                    <strong>David Miller Website</strong>.\r\n");
      out.write("                    <div class=\"text-muted smaller\">Today at 5:43 PM - 5m ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"list-group-item list-group-item-action\" href=\"#\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3 rounded-circle\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <strong>Samantha King</strong>sent you a new message!\r\n");
      out.write("                    <div class=\"text-muted smaller\">Today at 4:37 PM - 1hr ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"list-group-item list-group-item-action\" href=\"#\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3 rounded-circle\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <strong>Jeffery Wellings</strong>added a new photo to the album\r\n");
      out.write("                    <strong>Beach</strong>.\r\n");
      out.write("                    <div class=\"text-muted smaller\">Today at 4:31 PM - 1hr ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"list-group-item list-group-item-action\" href=\"#\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                  <img class=\"d-flex mr-3 rounded-circle\" src=\"http://placehold.it/45x45\" alt=\"\">\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <i class=\"fa fa-code-fork\"></i>\r\n");
      out.write("                    <strong>Monica Dennis</strong>forked the\r\n");
      out.write("                    <strong>startbootstrap-sb-admin</strong>repository on\r\n");
      out.write("                    <strong>GitHub</strong>.\r\n");
      out.write("                    <div class=\"text-muted smaller\">Today at 3:54 PM - 2hrs ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"list-group-item list-group-item-action\" href=\"#\">View all activity...</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-footer small text-muted\">Updated yesterday at 11:59 PM</div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container-fluid-->\r\n");
      out.write("    <!-- /.content-wrapper-->\r\n");
      out.write("    <footer class=\"sticky-footer\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("          <small>Copyright © Your Website 2017</small>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("      <i class=\"fa fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("    <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("            <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("              <span aria-hidden=\"true\">×</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("          <div class=\"modal-footer\">\r\n");
      out.write("            <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"../../pages/login.jsp\">Logout</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/popper/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("    <!-- Page level plugin JavaScript-->\r\n");
      out.write("    <script src=\"vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"vendor/datatables/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"js/sb-admin.min.js\"></script>\r\n");
      out.write("    <!-- Custom scripts for this page-->\r\n");
      out.write("    <script src=\"js/sb-admin-datatables.min.js\"></script>\r\n");
      out.write("    <script src=\"js/sb-admin-charts.min.js\"></script>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
